modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="ragemod"
version="2.0: Snapshot 22w"
displayName="RageMod"
credits="https://www.curseforge.com/minecraft/mc-mods/ragemod-by-rageteam"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ragemod-by-rageteam"
logoFile="logo.png"
authors="CrashGyuluka, Lyof"

[[dependencies.ragemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




