modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="ragemod"
version="2.02214"
displayName="[ RageMod ]"
credits="CrashGyuluka, Lyof"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ragemod-by-rageteam"
logoFile="logo.png"
authors="CrashGyuluka"
description='''
RageMod - Forge 
'''

[[dependencies.ragemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




